name: accounting_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.8.0
  auto_route: ^8.0.3
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3

  flutter_toggle_tab: ^1.4.1
  flutter_slidable: ^3.1.0

  firebase_messaging: ^14.2.2
  firebase_core: ^2.21.0
  firebase_remote_config: ^4.3.3

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
     - assets/images/
     - assets/images/tab-icons/
     - assets/images/settings/
     - assets/images/news/
     - assets/images/elements/
     - assets/images/finance/


  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/SFProDisplay-Regular.ttf
        - asset: fonts/SFProDisplay-Light.ttf
        - asset: fonts/SFProDisplay-Medium.ttf
        - asset: fonts/SFProDisplay-Bold.ttf
        - asset: fonts/SFProDisplay-Semibold.ttf
        - asset: fonts/SFProDisplay-Black.ttf
